### ISSUE TITLE
Whitelist - ConfigParser Error

### ISSUE THREAD

**Issue by xg5-simon** [armbues/ioc_parser#22]
Receive the following traceback when using the -p whitelist parameter with provided whitelist_*.ini files. 

```
Traceback (most recent call last):
  File "iocp.py", line 298, in <module>
    parser = IOC_Parser(args.INI, args.INPUT_FORMAT, args.DEDUP, args.LIB, args.OUTPUT_FORMAT)
  File "iocp.py", line 88, in __init__
    self.load_patterns(patterns_ini)
  File "iocp.py", line 117, in load_patterns
    config.readfp(f)
  File "C:\Python27\lib\ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "C:\Python27\lib\ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: whitelist_Host.ini, line: 1
'acm.org$\n'
```

**Comment by xg5-simon** [comment]
Closing issue. Using wrong parameter. Need to use -p "patterns.ini" and not the explicit whitelist file.
